### ISSUE TITLE
"send message" reply bug

### ISSUE THREAD

**Issue by Svxy** [CxWatcher/Kick-rate-limit-bypass#1]
when loading the script and sending a message with the trollface button, after replying to a user normally beforehand, regardless of if spamming or not, each message sent with the button shows up as a reply to the last message that the user replied to before.

this is just an issue i encountered im too lazy to show a demonstration or try to pr

**Comment by CxWatcher** [comment]
This means you clicked the message, it would have highlighted green

To exit out of reply mode, click another users message twice so it goes green and then back to grey
